// <auto-generated />
using CharactersWithoutNumber.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CharactersWithoutNumber.Migrations
{
    [DbContext(typeof(CharacterContext))]
    partial class CharacterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CharactersWithoutNumber.Models.Character", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Background");

                    b.Property<int>("Charisma");

                    b.Property<string>("Class");

                    b.Property<int>("Constitution");

                    b.Property<int>("Dexterity");

                    b.Property<string>("Faction");

                    b.Property<string>("Gender");

                    b.Property<string>("Homeworld");

                    b.Property<int>("Intelligence");

                    b.Property<string>("Name");

                    b.Property<string>("PartialClasses");

                    b.Property<string>("Species");

                    b.Property<int>("Strength");

                    b.Property<int>("StrengthModifier");

                    b.Property<int>("StrengthModifierBonus");

                    b.Property<int>("Wisdom");

                    b.HasKey("ID");

                    b.ToTable("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
